Todo/Models/Forms/LoginForm.cs
using System.ComponentModel.DataAnnotations;

namespace Todo.Models.Forms
{
	public class LoginForm
	{
		[Required(ErrorMessage = "Empty Login")]
		public string Login { get; set; }
		
		[Required(ErrorMessage = "Empty Password")]
		public string Password { get; set; }
	}
}

Todo/Models/Forms/UserRegistrationForm.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Todo.Models.Forms
{
	public class UserRegistrationForm
	{
		[Required(ErrorMessage = "Empty Name")]
		[MaxLength(64, ErrorMessage = "Max Name length is 64 symbols")]
		public string Name { get; set; }
		
		[Required(ErrorMessage = "Empty Login")]
		[MaxLength(64, ErrorMessage = "Max Login length is 64 symbols")]
		public string Login { get; set; }
		
		[Required(ErrorMessage = "Empty Password")]
		[MaxLength(64, ErrorMessage = "Max Password length is 64 symbols")]
		[MinLength(8, ErrorMessage = "Min Password length is 8 symbols")]
		public string Password { get; set; }

		[Required(ErrorMessage = "Passwords confirmation requred")]
		[MaxLength(64, ErrorMessage = "Min Password Confirmation length is 8 symbols")]
		[MinLength(8, ErrorMessage = "Min Password Confirmation length is 8 symbols")]
		[CompareAttribute("Password", ErrorMessage = "Passwords don't match.")]
		public string Password2 { get; set; }
	}
}

Todo/Models/User.Context.cs

namespace Todo.Models
{

	using System;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;


	public partial class UserDbContext : DbContext
	{
		public UserDbContext()
			: base("name=TodoConnection")
		{

		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
		{
			throw new UnintentionalCodeFirstException();
		}


		public virtual DbSet<User> Users { get; set; }

	}

}


Todo/Models/User.Designer.cs
// T4 code generation is enabled for model 'E:\C#\Todo\Todo\Models\User.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Todo/Models/User.cs
namespace Todo.Models
{
	using System;
	using System.Collections.Generic;

	public partial class User
	{
		public User()
		{
			RegistrationDate = DateTime.Now;
		}

		public long ID { get; set; }
		public string Name { get; set; }
		public Nullable<System.DateTime> RegistrationDate { get; set; }
		public string Login { get; set; }
		public string PasswordHash { get; set; }
	}
}

Todo/Controllers/MainController.cs
using System.Web.Mvc;
using Todo.Models;
using Todo.Interfaces;

namespace Todo.Controllers
{
	public class MainController : Controller
	{
		protected IUserRepository userRepository;

		public MainController(IUserRepository repository) { 
			userRepository = repository;
		}

		// GET: /Main/Index
		[Authorize]
		public ActionResult Index()
		{
			return View(userRepository.Users);
		}
	}
}

Todo/Controllers/UserController.cs
using System;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web.Helpers;
using System.Web.Mvc;
using Todo.Helpers;
using Todo.Interfaces;
using Todo.Models;
using Todo.Models.Forms;

namespace Todo.Controllers
{
	public class UserController : Controller
	{
		private IUserRepository userRepository = null;
		private IAuthProvider authProvider = null;

		public UserController(IUserRepository repository, IAuthProvider provider)
		{ 
			userRepository = repository;
			authProvider = provider;
		}

		// GET: /Account/Register
		[AllowAnonymous]
		public ActionResult Register()
		{
			return View();
		}

		[HttpPost]
		public JsonResult New(UserRegistrationForm userRegistrationForm)
		{
			if (userRegistrationForm == null)
			{ 
				return Json(JsonHelper.CreateErrorResponse("Bad Request"));
			}

			if (TryValidateModel(userRegistrationForm))
			{
				var errors = new string[] { };
				var user = new User() {
					Login = userRegistrationForm.Login.Trim(),
					Name = userRegistrationForm.Name.Trim(),
					PasswordHash = PasswordHelper.CreateHash(userRegistrationForm.Password)
				};

				try
				{
					userRepository.Save(user);

					return Json(new { errors = Enumerable.Empty<string>().ToArray() });
				}
				catch (DbEntityValidationException ex) //db validation errors
				{
					errors = ex.EntityValidationErrors.SelectMany(v => v.ValidationErrors).Select(e => e.ErrorMessage).ToArray<string>();
				}
				catch (DbUpdateException ex)
				{
					errors = new string[] { "Login already registered" };
				}
				catch (Exception ex)
				{
					errors = new string[] { ex.Message };
				}

				return Json(JsonHelper.CreateErrorResponse(errors));
			}
			else
			{
				var allErrors = ModelState.Values.SelectMany(v => v.Errors).Select(x => x.ErrorMessage);
				return Json(JsonHelper.CreateErrorResponse(allErrors));
			}
		}

		// GET: Login
		[HttpGet]
		[ActionName("Login")]
		public ActionResult LoginRender()
		{
			return View();
		}

		// POST: Login
		[HttpPost]
		public JsonResult Login(LoginForm loginForm)
		{
			if (loginForm == null)
			{ 
				return Json(JsonHelper.CreateErrorResponse("Bad Request"));
			}

			if (TryValidateModel(loginForm))
			{
				var errors = new string[] { };

				try
				{
					if (!authProvider.Authenticate(loginForm.Login, loginForm.Password))
					{
						errors = new string[] { "Login or password is incorrect" };
					}
				}
				catch (Exception ex)
				{
					errors = new string[] { ex.Message };
				}

				return Json(JsonHelper.CreateErrorResponse(errors));
			}
			else
			{
				var allErrors = ModelState.Values.SelectMany(v => v.Errors).Select(x => x.ErrorMessage);
				return Json(JsonHelper.CreateErrorResponse(allErrors));
			}
		}

		// GET: Logout
		[HttpPost]
		public JsonResult Logout()
		{
			authProvider.Logout();
			return Json(JsonHelper.CreateErrorResponse(new string[] { }));
		}
	}
}

Todo/Views/Main/Index.cshtml
@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<Todo.Models.User>

<div class="container" ng-controller="ListController">
	@if (@Request.IsAuthenticated)
	{
		<button class="btn btn-default" ng-click="logout()">
			Logout
		</button>
	}

	@foreach (var item in Model)
	{
		<div class="row">
			<div class="col-xs-3">
				@Html.DisplayFor(modelItem => item.Name)
			</div>

			<div class="col-xs-3">
				@Html.DisplayFor(modelItem => item.RegistrationDate)
			</div>

			<div class="col-xs-3">
				@Html.DisplayFor(modelItem => item.Login)
			</div>

			<div class="col-xs-3">
				@Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
				@Html.ActionLink("Details", "Details", new { id = item.ID })  |
				@Html.ActionLink("Delete", "Delete", new { id = item.ID })
			</div>
		</div>
	}
</div>

@Html.ActionLink("Register Link", "Register", "Main")

Todo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="TodoApp">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/vendor")
    @Scripts.Render("~/Scripts/app")
</body>
</html>

Todo/Views/User/Login.cshtml

@{
	ViewBag.Title = "Login";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
	<div class="col-xs-12 col-sm-6 col-sm-offset-3">
		<div class="panel panel-default" ng-controller="LoginController">
			<form name="loginForm">
				<fieldset>
					<div class="panel-heading">Login Form</div>

					<div class="panel-body">
						<div class="form-group">
							<input type="text" class="form-control" placeholder="Login" ng-model="user.Login" required>
						</div>

						<div class="form-group">
							<input type="password" class="form-control" placeholder="Password" ng-model="user.Password" required>
						</div>

						<div class="form-group" ng-show="errors.length">
							@Html.Partial("Error")
						</div>

						<div class="form-group" role="group">
							<button type="button" class="btn btn-default" ng-click="login()" ng-disabled="loginForm.$invalid">Login</button>
						</div>
					</div>
				</fieldset>
			</form>
		</div>
	</div>
</div>

Todo/Views/User/Register.cshtml

@{
	ViewBag.Title = "Register";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
	<div class="col-xs-12 col-sm-6 col-sm-offset-3" ng-controller="RegisterController">
		<div class="panel panel-default" ng-hide="registered">
			<form name="registerForm">
				<fieldset>
					<div class="panel-heading">Register</div>

					<div class="panel-body">
						<div class="form-group">
							<input type="text" class="form-control" placeholder="Name" ng-model="user.Name" required>
						</div>

						<div class="form-group">
							<input type="text" class="form-control" placeholder="Username" ng-model="user.Login" required>
						</div>

						<div class="form-group">
							<input type="password" class="form-control" placeholder="Password" ng-model="user.Password" required>
						</div>

						<div class="form-group">
							<input type="password" class="form-control" placeholder="Password Confirmation" ng-model="user.Password2" required>
						</div>

						<div class="form-group" ng-show="errors.length">
							@Html.Partial("Error")
						</div>

						<div class="form-group" role="group">
							<button type="button" class="btn btn-default" ng-click="register()" ng-disabled="registerForm.$invalid">Register</button>
						</div>
					</div>
				</fieldset>
			</form>
		</div>

		<div class="well" ng-show="registered">
			Registration is successful!<br />
			Now you can @Html.ActionLink("login", "Login")
		</div>
	</div>
</div>